/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddButton: typeof import('./src/components/AddButton.vue')['default']
    BottomNavigation: typeof import('./src/components/BottomNavigation.vue')['default']
    CardView: typeof import('./src/components/CardView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopBar: typeof import('./src/components/TopBar.vue')['default']
  }
}
